name:                aws-simple
version:             0.2.0.0
synopsis:            Dead simple bindings to commonly used AWS Services
description:         Please see README.md
homepage:            https://github.com/agrafix/aws-simple#readme
license:             MIT
author:              Alexander Thiemann
maintainer:          mail@athiemann.net
copyright:           2016 Alexander Thiemann <mail@athiemann.net>
category:            Web
extra-source-files:
  - README.md
  - package.yaml
  - stack.yaml

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - mtl
  - resourcet
  - lens
  - conduit
  - amazonka
  - amazonka-core
  - amazonka-s3
  - amazonka-sqs
  - blaze-builder
  - unordered-containers

library:
  source-dirs: src
  exposed-modules:
    - Network.AWS.Simple
