name:                aws-simple
version:             0.6.0.0
synopsis:            Simple bindings to commonly used AWS Services
description:         Simple bindings to commonly used AWS services
homepage:            https://github.com/agrafix/aws-simple#readme
license:             MIT
author:              Alexander Thiemann
maintainer:          mail@athiemann.net
copyright:           2016 - 2022 Alexander Thiemann <mail@athiemann.net>
category:            Web
extra-source-files:
  - README.md
  - package.yaml
  - stack.yaml

dependencies:
  - base >= 4.7 && < 5
  - text >= 1.2
  - bytestring >= 0.10
  - mtl >= 2.2
  - resourcet >= 1.0
  - lens >= 3.0
  - conduit >= 1.2
  - amazonka >= 2.0
  - amazonka-core
  - amazonka-s3
  - amazonka-sqs
  - unordered-containers >= 0.2
  - timespan >= 0.3

library:
  source-dirs: src
  exposed-modules:
    - Network.AWS.Simple
