name:                aws-simple
version:             0.4.0.0
synopsis:            Dead simple bindings to commonly used AWS Services
description:         Simple bindings to commonly used AWS services
homepage:            https://github.com/agrafix/aws-simple#readme
license:             MIT
author:              Alexander Thiemann
maintainer:          mail@athiemann.net
copyright:           2016 - 2017 Alexander Thiemann <mail@athiemann.net>
category:            Web
extra-source-files:
  - README.md
  - package.yaml
  - stack.yaml

dependencies:
  - base >= 4.7 && < 5
  - text >= 1.2
  - bytestring >= 0.10
  - mtl >= 2.2
  - resourcet >= 1.0
  - lens >= 3.0
  - conduit >= 1.2
  - amazonka >= 1.4.5
  - amazonka-core >= 1.4.5
  - amazonka-s3 >= 1.4.5
  - amazonka-sqs >= 1.4.5
  - unordered-containers >= 0.2
  - timespan >= 0.3

library:
  source-dirs: src
  exposed-modules:
    - Network.AWS.Simple
