resolver: lts-7.15
packages:
  - .
extra-deps:
  - http-client-0.5.5
  - http-client-tls-0.3.3.1
  - http-conduit-2.2.3
  - amazonka-core-1.4.5
  - amazonka-1.4.5
  - amazonka-s3-1.4.5
  - amazonka-sqs-1.4.5
