resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/17.yaml
packages:
  - .
extra-deps:
  - git: https://github.com/brendanhay/amazonka.git
    commit: 098795f847df7239af64535c6b2b233f3fbd699c
    subdirs:
      - lib/amazonka
      - lib/amazonka-core
      - lib/services/amazonka-sso
      - lib/services/amazonka-sts
      - lib/services/amazonka-s3
      - lib/services/amazonka-sqs
